<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="skillDefinition" nsURI="http://www.ecore.org/service/SkillDefinition"
    nsPrefix="SkillDefinition">
  <eClassifiers xsi:type="ecore:EClass" name="SkillDefinitionModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" eType="#//SkillDefinitionRepository"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SkillDefinitionRepository">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sets" upperBound="-1" eType="#//SkillDefinitionSet"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SkillDefinitionSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="skills" upperBound="-1"
        eType="#//SkillDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SkillDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inAttribute" upperBound="-1"
        eType="ecore:EClass ../../org.ecore.base.basicAttributes/model/basicAttributes.ecore#//AttributeDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outAttribute" upperBound="-1"
        eType="ecore:EClass ../../org.ecore.base.basicAttributes/model/basicAttributes.ecore#//AttributeDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" lowerBound="1"
        upperBound="-1" eType="#//SkillResult" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SkillResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="result" eType="#//SKILL_RESULT_TYPES"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SKILL_RESULT_TYPES">
    <eLiterals name="SUCCESS"/>
    <eLiterals name="ERROR" value="1"/>
  </eClassifiers>
</ecore:EPackage>
