<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="communicationPattern" nsURI="http://www.eclipse.org/smartmdsd/service/communicationPattern"
    nsPrefix="communicationPattern">
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationPattern" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PushPattern" eSuperTypes="#//ForkingPattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.smartmdsd.ecore.service.communicationObject/model/communicationObject.ecore#//CommunicationObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryPattern" eSuperTypes="#//RequestAnswerPattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestType" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.smartmdsd.ecore.service.communicationObject/model/communicationObject.ecore#//CommunicationObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="answerType" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.smartmdsd.ecore.service.communicationObject/model/communicationObject.ecore#//CommunicationObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventPattern" eSuperTypes="#//ForkingPattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventType" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.smartmdsd.ecore.service.communicationObject/model/communicationObject.ecore#//CommunicationObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activationType" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.smartmdsd.ecore.service.communicationObject/model/communicationObject.ecore#//CommunicationObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventStateType" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.smartmdsd.ecore.service.communicationObject/model/communicationObject.ecore#//CommunicationObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SendPattern" eSuperTypes="#//JoiningPattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.smartmdsd.ecore.service.communicationObject/model/communicationObject.ecore#//CommunicationObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForkingPattern" abstract="true" eSuperTypes="#//OneWayCommunicationPattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="JoiningPattern" abstract="true" eSuperTypes="#//OneWayCommunicationPattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequestAnswerPattern" abstract="true"
      eSuperTypes="#//TwoWayCommunicationPattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="OneWayCommunicationPattern" abstract="true"
      eSuperTypes="#//CommunicationPattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="TwoWayCommunicationPattern" abstract="true"
      eSuperTypes="#//CommunicationPattern"/>
</ecore:EPackage>
