<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="systemParameter" nsURI="http://www.ecore.org/system/SystemParameter"
    nsPrefix="SystemParameter">
  <eClassifiers xsi:type="ecore:EClass" name="SystemParamModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//ComponentParameterInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="system" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.system.componentArchitecture/model/componentArchitecture.ecore#//SystemComponentArchitecture"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentParameterInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstance" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.system.componentArchitecture/model/componentArchitecture.ecore#//ComponentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ParameterRefinement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentParam" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.component.componentParameter/model/componentParameter.ecore#//ComponentParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterRefinement" eSuperTypes="../../org.ecore.base.documentation/model/documentation.ecore#//AbstractDocumentedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.component.componentParameter/model/componentParameter.ecore#//ComponentParameterBase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass ../../org.ecore.base.basicAttributes/model/basicAttributes.ecore#//AttributeRefinement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterStructInstance" eSuperTypes="../../org.ecore.system.componentArchitecture/model/componentArchitecture.ecore#//ComponentInstanceExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="#//ComponentParameterInstance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
  </eClassifiers>
</ecore:EPackage>
