<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="causeEffectChain" nsURI="http://www.ecore.org/system/CauseEffectChain"
    nsPrefix="CauseEffectChain">
  <eClassifiers xsi:type="ecore:EClass" name="CuaseEffectChainModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chains" upperBound="-1"
        eType="#//ActivityChain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actArch" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.system.activityArchitecture/model/activityArchitecture.ecore#//ActivityArchitectureModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityChain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chainLinks" upperBound="-1"
        eType="#//AbstractChainLink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="desiredMinResponse" eType="#//MinResponseTime"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="desiredMaxResponse" eType="#//MaxResponseTime"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractChainLink" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityLink" eSuperTypes="#//AbstractChainLink">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="ecore:EClass ../../org.ecore.system.activityArchitecture/model/activityArchitecture.ecore#//ActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputHandlerLink" eSuperTypes="#//AbstractChainLink">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="ecore:EClass ../../org.ecore.system.activityArchitecture/model/activityArchitecture.ecore#//InputHandlerNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaxResponseTime">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1" eType="ecore:EEnum ../../org.ecore.system.activityArchitecture/model/activityArchitecture.ecore#//TimeUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MinResponseTime">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1" eType="ecore:EEnum ../../org.ecore.system.activityArchitecture/model/activityArchitecture.ecore#//TimeUnit"/>
  </eClassifiers>
</ecore:EPackage>
