<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="seronetExtension" nsURI="http://www.ecore.org/component/SeronetExtension"
    nsPrefix="SeronetExtension">
  <eClassifiers xsi:type="ecore:EClass" name="SupportedMiddleware" eSuperTypes="../../org.ecore.component.componentDefinition/model/componentDefinition.ecore#//ComponentPortExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="middleware" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.service.roboticMiddleware/model/roboticMiddleware.ecore#//RoboticMiddleware"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlainOpcUaPort" abstract="true" eSuperTypes="../../org.ecore.component.componentDefinition/model/componentDefinition.ecore#//AbstractComponentElement ../../org.ecore.base.mixedport/model/mixedport.ecore#//MixedPortOpcUaBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpcUaDeviceClient" eSuperTypes="#//PlainOpcUaPort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opcuaXmlFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpcUaReadServer" eSuperTypes="#//PlainOpcUaPort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outPort" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.component.componentDefinition/model/componentDefinition.ecore#//OutputPort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="4840"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpcUaClientLink" eSuperTypes="../../org.ecore.component.componentDefinition/model/componentDefinition.ecore#//AbstractComponentLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" lowerBound="1"
        eType="#//OpcUaDeviceClient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MixedPortROS" eSuperTypes="../../org.ecore.component.componentDefinition/model/componentDefinition.ecore#//DerivedComponentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass ../../org.ecore.base.mixedport/model/mixedport.ecore#//MixedPortROSBase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MixedPortYARP" eSuperTypes="../../org.ecore.component.componentDefinition/model/componentDefinition.ecore#//DerivedComponentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass ../../org.ecore.base.mixedport/model/mixedport.ecore#//MixedPortYARPBase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MixedPortROSLink" eSuperTypes="../../org.ecore.component.componentDefinition/model/componentDefinition.ecore#//AbstractComponentLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mixedportros" lowerBound="1"
        eType="#//MixedPortROS"/>
  </eClassifiers>
</ecore:EPackage>
