<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="compArchBehaviorExtension" nsURI="http://www.eclipse.org/smartmdsd/system/compArchBehaviorExtension"
    nsPrefix="compArchBehaviorExtension">
  <eClassifiers xsi:type="ecore:EClass" name="CoordinationModuleMapping" eSuperTypes="../../org.eclipse.smartmdsd.ecore.system.componentArchitecture/model/componentArchitecture.ecore#//SystemExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordModuleInst" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.smartmdsd.ecore.behavior.taskRealization/model/taskRealization.ecore#//AbstractCoordinationModuleInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordModReal" eType="ecore:EClass ../../org.eclipse.smartmdsd.ecore.behavior.skillRealization/model/skillRealization.ecore#//CoordinationModuleRealization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordInterCompInstMapping"
        lowerBound="1" upperBound="-1" eType="#//CoordinationInterfaceComponentInstanceMapping"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoordinationInterfaceComponentInstanceMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compInst" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.smartmdsd.ecore.system.componentArchitecture/model/componentArchitecture.ecore#//ComponentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordInterInst" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.smartmdsd.ecore.behavior.skillRealization/model/skillRealization.ecore#//CoordinationInterfaceInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskRealizationModelRef" eSuperTypes="../../org.eclipse.smartmdsd.ecore.system.componentArchitecture/model/componentArchitecture.ecore#//SystemExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskModelRef" eType="ecore:EClass ../../org.eclipse.smartmdsd.ecore.behavior.taskRealization/model/taskRealization.ecore#//TaskRealizationModel"/>
  </eClassifiers>
</ecore:EPackage>
