<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="compArchSeronetExtension" nsURI="http://www.eclipse.org/smartmdsd/system/compArchSeronetExtension"
    nsPrefix="compArchSeronetExtension">
  <eClassifiers xsi:type="ecore:EClass" name="OpcUaDeviceClientInstance" eSuperTypes="../../org.eclipse.smartmdsd.ecore.system.componentArchitecture/model/componentArchitecture.ecore#//ComponentInstanceExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceClient" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.smartmdsd.ecore.component.seronetExtension/model/seronetExtension.ecore#//OpcUaDeviceClient"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceURI" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpcUaReadServerInstance" eSuperTypes="../../org.eclipse.smartmdsd.ecore.system.componentArchitecture/model/componentArchitecture.ecore#//ComponentInstanceExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="readServer" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.smartmdsd.ecore.component.seronetExtension/model/seronetExtension.ecore#//OpcUaReadServer"/>
  </eClassifiers>
</ecore:EPackage>
