/**
 */
package org.ecore.component.componentDocumentation.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.ecore.component.componentDocumentation.util.ComponentDocumentationAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ComponentDocumentationItemProviderAdapterFactory extends ComponentDocumentationAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComponentDocumentationItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ecore.component.componentDocumentation.ComponentDocumentation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentDocumentationItemProvider componentDocumentationItemProvider;

	/**
	 * This creates an adapter for a {@link org.ecore.component.componentDocumentation.ComponentDocumentation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentDocumentationAdapter() {
		if (componentDocumentationItemProvider == null) {
			componentDocumentationItemProvider = new ComponentDocumentationItemProvider(this);
		}

		return componentDocumentationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ecore.component.componentDocumentation.ComponentServiceDocu} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentServiceDocuItemProvider componentServiceDocuItemProvider;

	/**
	 * This creates an adapter for a {@link org.ecore.component.componentDocumentation.ComponentServiceDocu}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentServiceDocuAdapter() {
		if (componentServiceDocuItemProvider == null) {
			componentServiceDocuItemProvider = new ComponentServiceDocuItemProvider(this);
		}

		return componentServiceDocuItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ecore.component.componentDocumentation.ComponentModeDocu} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentModeDocuItemProvider componentModeDocuItemProvider;

	/**
	 * This creates an adapter for a {@link org.ecore.component.componentDocumentation.ComponentModeDocu}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentModeDocuAdapter() {
		if (componentModeDocuItemProvider == null) {
			componentModeDocuItemProvider = new ComponentModeDocuItemProvider(this);
		}

		return componentModeDocuItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ecore.component.componentDocumentation.NeutralModeDocu} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NeutralModeDocuItemProvider neutralModeDocuItemProvider;

	/**
	 * This creates an adapter for a {@link org.ecore.component.componentDocumentation.NeutralModeDocu}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNeutralModeDocuAdapter() {
		if (neutralModeDocuItemProvider == null) {
			neutralModeDocuItemProvider = new NeutralModeDocuItemProvider(this);
		}

		return neutralModeDocuItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.ecore.component.componentDocumentation.CoordinationSlavePortDocu} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CoordinationSlavePortDocuItemProvider coordinationSlavePortDocuItemProvider;

	/**
	 * This creates an adapter for a {@link org.ecore.component.componentDocumentation.CoordinationSlavePortDocu}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCoordinationSlavePortDocuAdapter() {
		if (coordinationSlavePortDocuItemProvider == null) {
			coordinationSlavePortDocuItemProvider = new CoordinationSlavePortDocuItemProvider(this);
		}

		return coordinationSlavePortDocuItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (componentDocumentationItemProvider != null)
			componentDocumentationItemProvider.dispose();
		if (componentServiceDocuItemProvider != null)
			componentServiceDocuItemProvider.dispose();
		if (componentModeDocuItemProvider != null)
			componentModeDocuItemProvider.dispose();
		if (neutralModeDocuItemProvider != null)
			neutralModeDocuItemProvider.dispose();
		if (coordinationSlavePortDocuItemProvider != null)
			coordinationSlavePortDocuItemProvider.dispose();
	}

}
