<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="coordinationExtension" nsURI="http://www.ecore.org/component/CoordinationExtension"
    nsPrefix="CoordinationExtension">
  <eClassifiers xsi:type="ecore:EClass" name="PublicOperationMode" eSuperTypes="#//AbstractCoordinationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activates" upperBound="-1"
        eType="#//PrivateOperationMode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mode" lowerBound="1" eType="ecore:EClass ../../org.ecore.service.componentMode/model/componentMode.ecore#//ComponentModeDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefaultInit" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrivateOperationMode" eSuperTypes="#//AbstractCoordinationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoordinationSlavePort" eSuperTypes="../../org.ecore.component.componentDefinition/model/componentDefinition.ecore#//NamedComponentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//AbstractCoordinationElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.service.serviceDefinition/model/serviceDefinition.ecore#//CoordinationServiceDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCoordinationElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CoordinationMasterPort" eSuperTypes="../../org.ecore.component.componentDefinition/model/componentDefinition.ecore#//NamedComponentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.service.serviceDefinition/model/serviceDefinition.ecore#//CoordinationServiceDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationModeBinding" eSuperTypes="../../org.ecore.component.componentDefinition/model/componentDefinition.ecore#//ActivityExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mode" lowerBound="1" eType="#//PrivateOperationMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationServiceUsageRealization"
      eSuperTypes="#//AbstractCoordinationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceUsage" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.service.serviceDefinition/model/serviceDefinition.ecore#//CommunicationServiceUsage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentPort" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.component.componentDefinition/model/componentDefinition.ecore#//ComponentPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SkillRealizationsRef" eSuperTypes="#//AbstractCoordinationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="skillRealizationCoordModuleRef"
        lowerBound="1" eType="ecore:EClass ../../org.ecore.behavior.skillRealization/model/skillRealization.ecore#//CoordinationModuleRealization"/>
  </eClassifiers>
</ecore:EPackage>
