<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="taskRealization" nsURI="http://www.eclipse.org/smartmdsd/behavior/taskRealization"
    nsPrefix="taskRealization">
  <eClassifiers xsi:type="ecore:EClass" name="TaskRealizationModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//TaskRealization" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstCoordInst" upperBound="-1"
        eType="#//AbstractCoordinationModuleInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskRealization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskDef" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.smartmdsd.ecore.behavior.taskDefinition/model/taskDefinition.ecore#//TaskDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCoordinationModuleInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordModuleDef" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.smartmdsd.ecore.service.skillDefinition/model/skillDefinition.ecore#//CoordinationModuleDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
