<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="genericDatasheet" nsURI="http://www.ecore.org/base/genericDatasheet"
    nsPrefix="genericDatasheet">
  <eClassifiers xsi:type="ecore:EClass" name="DatasheetProperty" eSuperTypes="#//AbstractDatasheetElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semanticID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DefaultDatasheetProperties">
    <eLiterals name="Homepage"/>
    <eLiterals name="SpdxLicense" value="1"/>
    <eLiterals name="ProprietaryLicense" value="2"/>
    <eLiterals name="Purpose" value="3"/>
    <eLiterals name="TechnologyReadinessLevel" value="5"/>
    <eLiterals name="Supplier" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TechnologyReadinessLevel">
    <eLiterals name="TRL1"/>
    <eLiterals name="TRL2" value="1"/>
    <eLiterals name="TRL3" value="2"/>
    <eLiterals name="TRL4" value="3"/>
    <eLiterals name="TRL5" value="4"/>
    <eLiterals name="TRL6" value="5"/>
    <eLiterals name="TRL7" value="6"/>
    <eLiterals name="TRL8" value="7"/>
    <eLiterals name="TRL9" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericDatasheetModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//AbstractDatasheetElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDatasheetElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="MandatoryDatasheetElementNames">
    <eLiterals name="BaseURI"/>
    <eLiterals name="ShortDescription" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MandatoryDatasheetElement" eSuperTypes="#//AbstractDatasheetElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="#//MandatoryDatasheetElementNames"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
