<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="stateMachine" nsURI="http://www.ecore.org/base/StateMachine"
    nsPrefix="StateMachine">
  <eClassifiers xsi:type="ecore:EClass" name="StateTransition" eSuperTypes="#//AbstractMachineElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//AbstractStateElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//AbstractStateElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" lowerBound="1"
        eType="#//VisibilityType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//AbstractMachineElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMachineElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractStateElement" abstract="true"
      eSuperTypes="#//AbstractMachineElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//AbstractStateElement"/>
  <eClassifiers xsi:type="ecore:EEnum" name="VisibilityType">
    <eLiterals name="PUBLIC" literal="public"/>
    <eLiterals name="PRIVATE" value="1" literal="internal"/>
  </eClassifiers>
</ecore:EPackage>
