<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="serviceDefinition" nsURI="http://www.ecore.org/service/ServiceDefinition"
    nsPrefix="ServiceDefinition">
  <eClassifiers xsi:type="ecore:EClass" name="ServiceDefModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//CommRepoImport" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" eType="#//ServiceDefRepository"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceDefRepository" eSuperTypes="../../org.ecore.base.documentation/model/documentation.ecore#//AbstractDocumentedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="#//ServiceRepoVersion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//AbstractServiceDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractServiceDefinition" abstract="true"
      eSuperTypes="../../org.ecore.base.documentation/model/documentation.ecore#//AbstractDocumentedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//ServiceProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommRepoImport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceRepoVersion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="major" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationServiceDefinition" abstract="true"
      eSuperTypes="#//AbstractServiceDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="CoordinationServiceDefinition" eSuperTypes="#//AbstractServiceDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statePattern" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.service.coordinationPattern/model/coordinationPattern.ecore#//StatePattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterPattern" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.service.coordinationPattern/model/coordinationPattern.ecore#//ParameterPattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wiringPattern" eType="ecore:EClass ../../org.ecore.service.coordinationPattern/model/coordinationPattern.ecore#//DynamicWiringPattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitoringPattern" eType="ecore:EClass ../../org.ecore.service.coordinationPattern/model/coordinationPattern.ecore#//MonitoringPattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//CommunicationServiceUsage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForkingServiceDefinition" eSuperTypes="#//OneWayCommunicationService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.service.communicationPattern/model/communicationPattern.ecore#//ForkingPattern"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestAnswerServiceDefinition" eSuperTypes="#//TwoWayCommunicationService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.service.communicationPattern/model/communicationPattern.ecore#//RequestAnswerPattern"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OneWayCommunicationService" abstract="true"
      eSuperTypes="#//CommunicationServiceDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="TwoWayCommunicationService" abstract="true"
      eSuperTypes="#//CommunicationServiceDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationServiceUsage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uses" lowerBound="1" eType="#//CommunicationServiceDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoiningServiceDefinition" eSuperTypes="#//OneWayCommunicationService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
        eType="ecore:EClass ../../org.ecore.service.communicationPattern/model/communicationPattern.ecore#//JoiningPattern"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
